modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="galaxia"
version="1.0.0"
displayName="Galaxia"
credits="Massive thank you to TheGrayGhost for Minecraft By Example, which helped me immensely making this mod"
displayURL="https://github.com/TheGreyGhost"
authors="ElizaYami"

[[dependencies.galaxia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




